resources:
  pipelines:
  - pipeline: build
    source: 'Python packaging pipeline'
    trigger: true 
    
jobs:
- template: templates/py-package-test.yml
  parameters:
    arch: 'x86_64'
    machine_pool: 'Linux-CPU'

- template: templates/py-package-test.yml
  parameters:
    arch: 'aarch64'
    machine_pool: 'aiinfra-linux-ARM64-CPU-2019'